name: test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/checkout@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Test
          run: |
            python test.py

